Traceback (most recent call last):
  File "C:/Users/antho/Desktop/GitHub/git-repos/ATBS/raiseAndAssert.py", line 37, in <module>
    raise Exception('This is the error message.')
Exception: This is the error message.
